version: '3'
services:

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    container_name: backend
    restart: always 
    networks:
        - app_tier
    volumes:
       - ./backend:/app        
    command: gunicorn -w 1 -b 0.0.0.0:5000 run:app

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks: 
      - app_tier
    restart: "on-failure"

networks:  # 네트워크 이름 
  app_tier:
    driver: bridge  # 컨테이너를 bridge로 연결 